polar:
  greeting: "Intialize Test Data with Demo Profile`"

spring:
  datasource:
    username: postgres
    password: chiskien
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5