polar:
  greeting: "Welcome to ExcellentVile"

spring:
  datasource:
    username: postgres
    password: chiskien
    url: jdbc:postgresql://localhost:5432/excellentdb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5